typography_spectrum: 0.74277
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75048
analytics:
  google: null
  facebook: null
  twitter: null
name: perclingweld
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Love People. Love Life.
purpose: []
